# Generated by Django 5.1 on 2024-08-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_checkout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
