# Generated by Django 5.1 on 2024-08-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_remove_checkout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(),
        ),
    ]
