# Generated by Django 5.1 on 2024-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_alter_cart_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
