# Generated by Django 5.1 on 2024-08-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('base_price', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('stock', models.IntegerField()),
                ('trending', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('offer', models.BooleanField(default=False)),
                ('tag', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.category')),
            ],
        ),
    ]
